ansible_user                 : worker
# ansible_ssh_private_key_file : /home/leo/.ssh/london-k.pem
ansible_ssh_pass             : asd
ansible_become_pass          : asd
enviroment                   : STAGING
peremennaya                  : peremennaya
