ansible_user                 : root
# ansible_ssh_private_key_file : /home/leo/.ssh/london-k.pem
ansible_ssh_pass             : p@ssw0rd
# ansible_become_pass          : asd
enviroment                   : STAGING
peremennaya                  : peremennaya
