---
- name: Config Control Host
  hosts: ctrl_host
  vars_files:
    - vars/jenkins.yml
    - vars/ctrl_host.yml
    - vars/java.yml
  roles:
    - resolv
    - create_users_and_groups
    - ssh_create
    - ssh_manipulate
    - config_server
    - geerlingguy.java
    - geerlingguy.jenkins
#    - maven
    - firewall
  tasks:
    - name: Install creds for ansible
      authorized_key:
        user: ansible
        key: "{{ lookup('file', 'files/ansible/id_ansible_rsa.pub') }}"

- name: Config workers
  hosts: workers
  vars_files:
    - vars/workers.yml
  roles:
    - resolv
    - create_users_and_groups
    # - geerlingguy.java
    # - tomcat
    # - maven
    # - firewall
  tasks:
    - name: Install creds for ansible
      authorized_key:
        user: ansible
        key: "{{ lookup('file', 'files/ansible/id_ansible_rsa.pub') }}"

    - name: Install jenkins creds for root
      authorized_key:
        user: root
        key: "{{ lookup('file', 'files/jenkins/id_rsa.pub') }}"
- name: Config db
  hosts: db
  roles:
    - resolv
    - geerlingguy.mysql
    - download_deps
    - db_conf

# - name: Config gitlab
#   hosts: gitlab
# #   vars_files:
# #   roles:
#   tasks:
#     - name: Install jenkins creds for root
#       authorized_key:
#         user: root
#         key: "{{ lookup('file', 'files/jenkins/id_rsa.pub') }}"
