---
- name: Config Control Host
  hosts: ctrl_host
  vars_files:
    - vars/jenkins.yml
    - vars/ctrl_host.yml
    - vars/java.yml
  roles:
    - resolv
    - download_deps

    ##### Users and ssh-keys
    - create_users_and_groups
    - ssh_create
    - ssh_manipulate
    - install_creds

    - config_server
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.mysql
    - db_conf
    - maven
    - firewall


- name: Config workers
  hosts: workers
  vars_files:
    - vars/workers.yml
    - vars/java.yml
  roles:
    - resolv
    - download_deps

    ###### Users and ssh-keys
    - create_users_and_groups
    - install_creds
    
    - geerlingguy.java
    - tomcat
    - maven
    - firewall

- name: Config db
  hosts: db
  vars_files:
    - vars/db.yml
  roles:
    - resolv
    - download_deps
    - geerlingguy.mysql
    - db_conf
    - firewall